export const shoppingCartCases = {
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  ADD_QUANTITY_TO_ITEM: 'ADD_QUANTITY_TO_ITEM',
  REMOVE_QUANTITY_TO_ITEM: 'REMOVE_QUANTITY_TO_ITEM',
};
